Various improvements
jc-SpaceXp/cNES pull request #1
Opened 2018-11-21 20:53 UTC by francois-berder

* Fix build failure (obj directory was not created and SDL link errors)
  * Improve Makefile to support parallel builds
  * Fix warnings
  * Fix memory leaks in main
  * Better handling cartridge load failure

2018-12-21 17:46 UTC, jc-SpaceXp approved these changes
Approved.

2018-12-21 17:50 UTC, jc-SpaceXp commented
I didn't mean to approve all 12 commits initially, just one I was looking at.

2018-12-21 17:52 UTC, jc-SpaceXp commented
Many of these changes overlap with the cleanup branch that I've been working on recently i.e. malloc checking and SDL_Delay(). I will look over these changes over the next few days and merge appropriately.

2018-12-21 18:26 UTC, jc-SpaceXp requested changes
Can you please change the branch from master to cleanup. I understand you made the changes before I made the branch. Also can the missing void commit and the malloc checks for cpu and ppu structs be removed? They've been fixed in the cleanup branch a while ago and will create a small merge conflict.

2018-12-26 10:36 UTC, francois-berder commented
Hello,
In that case, I will close this pull request and open one later. Let me know if you merge cleanup branch to master.
François

2018-12-30 12:40 UTC, jc-SpaceXp commented
Hi,
I've just merged my cleanup branch to master.

2019-01-10 22:00 UTC, francois-berder commented
Hi, I've just rebased my patches on top of the master branch.

2019-02-05 20:19 UTC, jc-SpaceXp commented
Hi, I'm going to look through these changes soon!

2019-02-10 15:52 UTC, jc-SpaceXp commented on makefile
> +CFLAGS += -O2
O2 and O3 break emulator

2019-02-10 16:17 UTC, jc-SpaceXp commented on makefile
> +CONFIG ?= debug
DEBUG ?= 1

Then running: make DEBUG=0 seems better to me

2019-02-10 16:18 UTC, jc-SpaceXp commented on makefile
> +CFLAGS += -g
CFLAGS += -DDEBUG

2019-02-10 16:18 UTC, jc-SpaceXp commented on makefile
> +CFLAGS += -O2
CFLAGS += -DNDEBUG

2019-03-17 11:54 UTC, merged